name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Set up Python 3.8
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08
        with:
          python-version: 3.8

      - name: Upgrade system packages
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: python -m pip install .[test]

      - name: Test with pytest
        run: |
          python -m pytest